### ISSUE TITLE
Scrollbar not updated after cursor movements (zz, zt, zb)

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#543]
After using one of the cursor movements (zz, zt or zb), the scrollbar on the right side is not visually updated.

See:

![2017-07-17-133036_1365x228_scrot](https://user-images.githubusercontent.com/347552/28278643-26381eb8-6af4-11e7-8962-cec5dbb60e69.png)

**Comment by extr0py** [comment]
Nice catch! I'm able to repro this.

It looks like most of the autocmds we hook watch for cursor being moved - but in the case where the window scrolls, and the cursor doesn't move, the scrollbar isn't updated.

A potential fix is to update the scroll state when we get the `scroll` action during `redraw`.

**Comment by cyansprite** [comment]
It also doesn't update the linting errors.

**Comment by extr0py** [comment]
I have a partial fix - but it turns out there isn't a great way currently to detect this case. The autocmds we listen to work fine if the cursor moves, but in the case where the screen scrolls but the cursor _does not_ move, it's a bit less reliable.

Ideally, there'd be a `Scroll` autocmd we could listen to in order to give us this info. There's a tracking issue in neovim/neovim#4322

**Comment by cyansprite** [comment]
An idea...
it's not a fix but more of a hack, but if we get the keys pressed to do with scrolling, we can catch those keys, then send them to vim (like we do with all the other keys) and then after wards, redraw the screen.

**Comment by extr0py** [comment]
> An idea...
> it's not a fix but more of a hack, but if we get the keys pressed to do with scrolling, we can catch those  keys, then send them to vim (like we do with all the other keys) and then after wards, redraw the screen.

Ya, in a similiar vein, we could do something like:
``` nnoremap zt :Call ExecAndNotifyOni('zt')<CR>```

Like run the command on the Vim side, and then notify Oni that there was an update

**Comment by bryphe** [comment]
This was fixed by #805

**Comment by wellle** [comment]
@bryphe: I believe this is still not fully fixed, unfortunately.

To reproduce open a sufficiently large file and go to the middle of it by typing `50%`. Try alternate typing `zt` and `zb`. The visible lines in the buffer update accordingly, but the scroll bar only updates a single time. Interestingly if you type `zz` it updates both the visible lines and the scrollbar properly, and after that the next `zt` or `zb` works too. But if you start alternating them again they won't update the scrollbar anymore.

I tried it on `oni version 0.3.9` which seems to be the latest.
